apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkgfinder-ui-deployment
  labels:
    app: pkgfinder-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pkgfinder-ui
  template:
    metadata:
      labels:
        app: pkgfinder-ui
    spec:
      containers:
      - name: pkgfinder-ui
        image: marwanhawari/pkgfinder-ui
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: pkgfinder-ui-svc
spec:
  type: NodePort
  selector:
    app: pkgfinder-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
