apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkgfinder-api-deployment
  labels:
    app: pkgfinder-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pkgfinder-api
  template:
    metadata:
      labels:
        app: pkgfinder-api
    spec:
      containers:
      - name: pkgfinder-api
        image: marwanhawari/pkgfinder-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: pkgfinder-api-svc
spec:
  type: NodePort
  selector:
    app: pkgfinder-api
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30200